name: Scheduled Date Processor

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  process-dates:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify API endpoint
      run: |
        echo "Testing API connectivity..."
        if ! curl -m 5 -I https://ene-apply-batch-orchestrator.prod.joveo.com; then
          echo "API endpoint unreachable"
          exit 1
        fi

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pytz

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Process dates
      env:
        START_DATE: "20250610"
        END_DATE: "20250623"
        CTK_COOKIE: ${{ secrets.CTK_COOKIE }}
      run: |
        python3 .github/scripts/date_processor.py "$START_DATE" "$END_DATE" "$CTK_COOKIE"
        git add .github/scripts/state.json .github/scripts/processing_log.txt
        git commit -m "Update processing state [skip ci]" || echo "No changes to commit"
        git push

    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: processing-artifacts
        path: |
          .github/scripts/state.json
          .github/scripts/processing_log.txt